package bitcamp.java110.cms.dao.impl;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import bitcamp.java110.cms.dao.DaoException;
import bitcamp.java110.cms.dao.StudentDao;
import bitcamp.java110.cms.domain.Student;

public class StudentJdbcDao implements StudentDao {
    private List<Student> list=new ArrayList<>();
    
    
    public int insert (Student student) {
        Connection con=null;
        Statement stmt=null;
        
        try {
            
            
            Class.forName("org.mariadb.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mariadb://localhost:3306/studydb", "study", "1111");
            
            con.setAutoCommit(false);
            
            stmt = con.createStatement();
            String sql="     insert into p1_memb(name,email,pwd,tel,cdt)"
                            + " values('"+ student.getName()+ "' , '"+student.getEmail()
                            + "',password('" + student.getPassword() + "')"
                            + ",'"+student.getTel()
                            + "',now()) ";
            
            stmt.executeUpdate(sql, Statement.RETURN_GENERATED_KEYS);
            
            ResultSet autogeneratedKeys =stmt.getGeneratedKeys();
            autogeneratedKeys.next(); //이건뭐지?
            int memberNo=autogeneratedKeys.getInt(1);
            autogeneratedKeys.close();
            
            String work="N";
            if(student.getClass().equals(true)) {
                work="Y";
            }
            
            
            String sql2=" insert into p1_mgr(sno,schl,work)"
                    +   " values("+memberNo
                    + ",'"+student.getSchool()+"'"
                    + ",'"+work+"' )";
            
            stmt.executeQuery(sql2);
            
            //두개의 쿼리실행문이 완료됐을시에 commit시킴 
            con.commit();
            return 1;
        }catch(Exception e){
            throw new DaoException(e);
        }finally {
            try{stmt.close();} catch(Exception e) {}
            try{con.close();} catch(Exception e) {}
        }
    }
    
    public List<Student> findAll() {
    }
    
    public Student findByNo(int no) {
    }
    
    public int deleteByno(int no) {
    }

}
